MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.36"
SiteTitle: only the important stuff
Description: Hilarity ensues with Jeff and friends as they discuss life, parenthood, leadership and other really important stuff. For the Kids.
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
Copyright: => $"Copyright © {DateTime.Now.Year}"
PostSources: posts/**/*
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
Layout: /_layout.cshtml
Image: images/otis.jpg